version: '2.1'

services:
  dashqrweb:
    image: dashqrweb
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 8082:80
    ## set your startup file here
    #command: [nginx-debug, '-g', 'daemon off;']